"""
Research Agent State Schema

This module defines the complete state schema for the research agent graph.
It demonstrates the key LangGraph concept: explicit TypedDict + reducers.

Key learning point: Without reducers, list fields get REPLACED instead of APPENDED.
Use Annotated[list, operator.add] for fields that accumulate across multiple nodes.
"""

from __future__ import annotations

import operator
from typing import Annotated, Optional, TypedDict

from langchain_core.messages import BaseMessage


class SubQuestion(TypedDict, total=False):
    """A research sub-question generated by the planner."""

    id: str
    question: str
    findings: str  # filled by researcher node
    sources: list[str]  # URLs / citations


class QualityScore(TypedDict, total=False):
    """Evaluation of the draft report."""

    score: int  # 0-100
    feedback: str
    passed: bool


class ResearchState(TypedDict):
    """
    Complete state for the research agent graph.

    Key pattern: Use Annotated[list, operator.add] for fields that accumulate.
    This ensures each node's return value APPENDS to the list instead of REPLACING it.

    Without this, message history and finding accumulation would be lost.
    """

    # --- Input ---
    topic: str
    """The research topic provided by the user."""

    max_sub_questions: int
    """Maximum number of sub-questions to plan (default: 3)."""

    # --- Planning ---
    sub_questions: list[SubQuestion]
    """Sub-questions generated by planner node, populated by researcher nodes."""

    # --- Accumulation (CRITICAL: use reducer for append behavior) ---
    messages: Annotated[list[BaseMessage], operator.add]
    """Message history. Annotated reducer ensures APPEND behavior, not REPLACE.

    Without the reducer:
        def node(state): return {"messages": [new_msg]}
        -> REPLACES entire list (BAD)

    With the reducer:
        def node(state): return {"messages": [new_msg]}
        -> APPENDS to list (GOOD)

    This is the #1 gotcha for developers coming from LangChain.
    """

    # --- Synthesis ---
    draft_report: str
    """Draft report produced by synthesizer node."""

    quality: Optional[QualityScore]
    """Quality evaluation. None before quality_check runs."""

    human_feedback: Optional[str]
    """Feedback from human review (if using interrupt_before)."""

    # --- Control ---
    retry_count: int
    """Number of times the planner has been retried (for quality feedback)."""

    error: Optional[str]
    """Error message from failed operations (for error_handling node)."""

    final_report: str
    """Final formatted report (Markdown) produced by formatter node."""
